# Generated by Django 5.1.3 on 2024-11-23 05:22

from django.db import migrations

def add_default_data(apps, schema_editor):
    Author = apps.get_model('web', 'Author')
    Publisher = apps.get_model('web', 'Publisher')
    Book = apps.get_model('web', 'Book')

    author = Author.objects.create(name="Default Author")
    publisher = Publisher.objects.create(name="Default Publisher")
    Book.objects.create(
        title="Sample Book",
        author=author,
        publisher=publisher,
        price=19.99,
        publication_date="2024-01-01"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_author_publisher_book'),
    ]

    operations = [
        migrations.RunPython(add_default_data),
    ]
