name: Django CI with Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: django_db
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker-compose down
        docker-compose up -d --build

    - name: Run migrations
      run: |
        docker-compose exec web python manage.py makemigrations
        docker-compose exec web python manage.py migrate

    - name: Run tests with coverage
      run: |
        docker-compose exec web coverage run --source='.' manage.py test
        docker-compose exec web coverage report
        docker-compose exec web coverage xml

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2.3.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.xml